### ISSUE TITLE
mapShorelineCCD

### ISSUE THREAD

**Issue by SharifaKar** [conlin-matt/pyArgus_mpc#2]
Hi Matt,

This pythonic version of the mapShoreline codes is extremely helpful, thank you! I am having an issue with the mapshorelineCCD code, when masking the data outside of the ROI, the code breaks at im_dif[~inAr] = np.nan. Initially I thought it may be due to X,Y meshgrid created since using np.arange will cut off the max (my step was 0.5). I switched to np.linspace, but it still breaks at im_dif[~inAr] = np.nan. Do you have any suggestions?

Thank you,
Sharifa

**Comment by conlin-matt** [comment]
Hi Sharifa,

Awesome, I'm glad someone else is getting use out of this. What's the error message that you get?

**Comment by SharifaKar** [comment]
Actually, it doesn't show me any error messages,. Just at line 334 it breaks and goes back to my working code where I call mapshorelineCCD, so I'm not entirely sure. I've only changed the np.arange to np.linspace for creating the vectors for real-world coordinates (~lines 266-267). Sorry if that's kinda vague, it's stumped me.

**Comment by conlin-matt** [comment]
How do you know it breaks at L334? Can you share the code where you call the function?

**Comment by SharifaKar** [comment]
I put a breakpoint at l334 and it reverts back to my code. Sure, could you send me your email please?

**Comment by conlin-matt** [comment]
You can copy/paste code right here- I just want to see the line where you call the function and any import statements for this package

**Comment by SharifaKar** [comment]
Gotcha, the line is as follows:

# Identify the shoreline - CCD #
    try:
        if not h:
            c,h = s1.mapShorelineCCD(rectified_image,[xmin,xmax,dx,ymin,ymax,dy,z]) #rectified_image
        else:
            c,h = s1.mapShorelineCCD(rectified_image,[xmin,xmax,dx,ymin,ymax,dy,z], h) #rectified_image
    except:
        pass

it's within a for loop that rectifies a set number of oblique imagery. I don't have h predefined, so it goes into the if not h, breaks at l334 within mapshorelineCCD and then goes to the except statement.

**Comment by conlin-matt** [comment]
Ok. Does the figure window open and allow you to interactively select your four corners? It seems to me the issue is h never gets defined, which would be the case if you don't do the interactive picking. I don't know what interpreter you're using, but I wrote this for Spyder and this interactive picking code may not work with all interpreters. If you are using Spyder, I know you have to change the graphics backend to not be inline.

**Comment by conlin-matt** [comment]
Also you're not seeing an error message because it's being caught by your except line (which just moves on). To see the error message you can use:
```python
try:
   blah
except Exception as e:
   print(e)
```

**Comment by SharifaKar** [comment]
The interactive figure does pop up and allows me to select the four corners. I also see that h is populated after the clicking, but when the code breaks and returns to the except, h is []. I use VS Code and jupyter notebooks w/a virtual environment set up using a YAML file. But perhaps I should use Spyder?

**Comment by SharifaKar** [comment]
oh I see, it says **cannot convert float NaN to integer** when I added in the the bit of code you sent. I think I got it from here. Thanks Matt for helping me troubleshoot!
